name: Build and Release

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version tag
      id: tag
      run: |
        # Get the latest tag or start with v1.0.0
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $LATEST_TAG"
        
        # Extract version numbers
        VERSION_REGEX="v([0-9]+)\.([0-9]+)\.([0-9]+)"
        if [[ $LATEST_TAG =~ $VERSION_REGEX ]]; then
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          PATCH="${BASH_REMATCH[3]}"
        else
          MAJOR=1
          MINOR=0
          PATCH=0
        fi
        
        # Increment patch version
        PATCH=$((PATCH + 1))
        VERSION="v${MAJOR}.${MINOR}.${PATCH}"
        
        echo "tag=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: Password Generator ${{ steps.tag.outputs.tag }}
        body: |
          ## Password Generator Release ${{ steps.tag.outputs.tag }}
          
          ### Features
          - Modern CustomTkinter interface
          - Cross-platform compatibility
          - Password generation with customizable options
          - Theme support (Light/Dark/System)
          - One-click clipboard copy
          
          ### Downloads
          - **Windows**: `PasswordGenerator-windows.exe`
          - **macOS**: `PasswordGenerator-macos.dmg` (Double-click to mount, then drag to Applications)
          - **Linux**: `PasswordGenerator-linux`
          
          ### Installation
          Download the appropriate file for your operating system and run it directly - no Python installation required!
          
          Generated from commit: ${{ github.sha }}
        draft: false
        prerelease: false

  build-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name PasswordGenerator-windows --icon=icon.ico PasswordGenerator.py || pyinstaller --onefile --windowed --name PasswordGenerator-windows PasswordGenerator.py

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./dist/PasswordGenerator-windows.exe
        asset_name: PasswordGenerator-windows.exe
        asset_content_type: application/octet-stream

  build-macos:
    needs: create-release
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        brew install python-tk

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build macOS application
      run: |
        pyinstaller --onefile --windowed --name PasswordGenerator PasswordGenerator.py

    - name: Create macOS app bundle
      run: |
        mkdir -p "PasswordGenerator.app/Contents/MacOS"
        mkdir -p "PasswordGenerator.app/Contents/Resources"
        cp dist/PasswordGenerator "PasswordGenerator.app/Contents/MacOS/"
        
        # Create Info.plist with proper bundle structure
        cat > "PasswordGenerator.app/Contents/Info.plist" << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>PasswordGenerator</string>
            <key>CFBundleIdentifier</key>
            <string>com.github.passwordgenerator</string>
            <key>CFBundleName</key>
            <string>Password Generator</string>
            <key>CFBundleDisplayName</key>
            <string>Password Generator</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.0</string>
            <key>CFBundleVersion</key>
            <string>1.0.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleSignature</key>
            <string>????</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.13</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>NSRequiresAquaSystemAppearance</key>
            <false/>
        </dict>
        </plist>
        EOF
        
        # Make executable
        chmod +x "PasswordGenerator.app/Contents/MacOS/PasswordGenerator"
        
        # Remove quarantine attributes and sign with ad-hoc signature
        xattr -cr PasswordGenerator.app
        codesign --force --deep --sign - PasswordGenerator.app
        
        # Create disk image instead of zip for better compatibility
        hdiutil create -volname "Password Generator" -srcfolder PasswordGenerator.app -ov -format UDZO PasswordGenerator-macos.dmg

    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./PasswordGenerator-macos.dmg
        asset_name: PasswordGenerator-macos.dmg
        asset_content_type: application/octet-stream

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Linux executable
      run: |
        pyinstaller --onefile --name PasswordGenerator-linux PasswordGenerator.py

    - name: Make executable
      run: |
        chmod +x dist/PasswordGenerator-linux

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./dist/PasswordGenerator-linux
        asset_name: PasswordGenerator-linux
        asset_content_type: application/octet-stream

  notify-completion:
    needs: [create-release, build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
    - name: Notify completion
      run: |
        echo "✅ Release ${{ needs.create-release.outputs.tag_name }} completed successfully!"
        echo "📦 All platform builds have been uploaded to the release."